package dto

type Item struct {
	ReadonlyProperties           ReadonlyProperties `json:"ReadonlyProperties"`
	RentalObject                 RentalObject       `json:"RentalObject"`
	Bookmarked                   bool               `json:"Bookmarked"`
	MobilityBudget               float64            `json:"MobilityBudget"`
	CO2Budget                    int                `json:"CO2Budget"`
	AdditionalPayment            float64            `json:"AdditionalPayment"`
	IsPayback                    bool               `json:"IsPayback"`
	MobilityAdditionalPayment    float64            `json:"MobilityAdditionalPayment"`
	IsMobilityPayback            bool               `json:"IsMobilityPayback"`
	CO2AdditionalPayment         float64            `json:"CO2AdditionalPayment"`
	IsCO2Payback                 bool               `json:"IsCO2Payback"`
	MinMileage                   int                `json:"MinMileage"`
	MaxMileage                   int                `json:"MaxMileage"`
	CreatedDate                  MyTime          `json:"CreatedDate"`
	ExternalTariffGroup          interface{}        `json:"ExternalTariffGroup"`
	TarifElementIdents           interface{}        `json:"TarifElementIdents"`
	ImageIdents                  []string           `json:"ImageIdents"`
	ImageLinks                   []string           `json:"ImageLinks"`
	OfferTypeToken               string             `json:"OfferTypeToken"`
	OfferTypeName                string             `json:"OfferTypeName"`
	Active                       bool               `json:"Active"`
	Archived                     bool               `json:"Archived"`
	Tyretype                     string             `json:"Tyretype"`
	Color                        interface{}        `json:"Color"`
	KindOfGear                   interface{}        `json:"KindOfGear"`
	KindOfFuel                   interface{}        `json:"KindOfFuel"`
	Price                        float64            `json:"Price"`
	PriceGr                      float64            `json:"PriceGr"`
	UserdefinedOutfit2           interface{}        `json:"UserdefinedOutfit2"`
	MinimumAge                   interface{}        `json:"MinimumAge"`
	ShopInsuranceIdent           interface{}        `json:"ShopInsuranceIdent"`
	ShopServiceRegistrationIdent interface{}        `json:"ShopServiceRegistrationIdent"`
	MileagePerMonth              int                `json:"MileagePerMonth"`
	RuntimeMonths                int                `json:"RuntimeMonths"`
	TextblockDeliveryAdmission   interface{}        `json:"TextblockDeliveryAdmission"`
	TextblockMiscTerms           string             `json:"TextblockMiscTerms"`
	TextblockInsuranceTerms      string             `json:"TextblockInsuranceTerms"`
	MileageExtraPrice            float64            `json:"MileageExtraPrice"`
	MileageExtraPriceGr          float64            `json:"MileageExtraPriceGr"`
	ActiveInLzs                  interface{}        `json:"ActiveInLzs"`
	TextblockInsurance           interface{}        `json:"TextblockInsurance"`
	TextblockDelivery            interface{}        `json:"TextblockDelivery"`
	ColorCode                    interface{}        `json:"ColorCode"`
	MileageCount                 interface{}        `json:"MileageCount"`
	MaturityDays                 interface{}        `json:"MaturityDays"`
	Maturity                     interface{}        `json:"Maturity"`
	Mileage                      interface{}        `json:"Mileage"`
	MileageLevel2Count           interface{}        `json:"MileageLevel2Count"`
	MileageExtraLevel2Price      interface{}        `json:"MileageExtraLevel2Price"`
	MileageExtraLevel2PriceGr    interface{}        `json:"MileageExtraLevel2PriceGr"`
	UserdefinedOutfit1           interface{}        `json:"UserdefinedOutfit1"`
	Engine                       interface{}        `json:"Engine"`
	NaviIncluded                 interface{}        `json:"NaviIncluded"`
	CarSale                      interface{}        `json:"CarSale"`
	PriceUnit                    interface{}        `json:"PriceUnit"`
	AdversityLimit               interface{}        `json:"AdversityLimit"`
	Topoffer                     interface{}        `json:"Topoffer"`
	DeliveryBeginLocation        interface{}        `json:"DeliveryBeginLocation"`
	DeliveryEndLocation          interface{}        `json:"DeliveryEndLocation"`
	ExceedenceLevel1Days         interface{}        `json:"ExceedenceLevel1Days"`
	ExceedenceLevel1Price        interface{}        `json:"ExceedenceLevel1Price"`
	ExceedenceLevel1PriceGr      interface{}        `json:"ExceedenceLevel1PriceGr"`
	ExceedenceLevel2Days         interface{}        `json:"ExceedenceLevel2Days"`
	ExceedenceLevel2Price        interface{}        `json:"ExceedenceLevel2Price"`
	ExceedenceLevel2PriceGr      interface{}        `json:"ExceedenceLevel2PriceGr"`
	InsurancePriceFixedRate      interface{}        `json:"InsurancePriceFixedRate"`
	InsurancePrice               interface{}        `json:"InsurancePrice"`
	InsurancePriceGr             interface{}        `json:"InsurancePriceGr"`
	PriceInformation             interface{}        `json:"PriceInformation"`
	DeliveryPrice                interface{}        `json:"DeliveryPrice"`
	DeliveryPriceGr              interface{}        `json:"DeliveryPriceGr"`
	DeliveryPriceFixedRate       interface{}        `json:"DeliveryPriceFixedRate"`
	CostSharingTK                interface{}        `json:"CostSharingTK"`
	CostSharingVK                interface{}        `json:"CostSharingVK"`
	ProductGroup                 interface{}        `json:"ProductGroup"`
	CostPlace                    interface{}        `json:"CostPlace"`
	ExternalSourceID             interface{}        `json:"ExternalSourceId"`
	UseOfferTypePriceTemplate    bool               `json:"UseOfferTypePriceTemplate"`
	MappedTarifgroup             interface{}        `json:"MappedTarifgroup"`
	Ident                        string             `json:"Ident"`            
	SalaryWaiver                 float64            `json:"SalaryWaiver"`  
}
