package dto

import "time"

type LoginResponse struct {
	Content struct {
		AddressRole struct {
			AssignedPolicy interface{} `json:"AssignedPolicy"`
			Ident          string      `json:"Ident"`
			OwnerIdent     interface{} `json:"OwnerIdent"`
			RoleName       string      `json:"RoleName"`
		} `json:"AddressRole"`
		AddressToken               string      `json:"AddressToken"`
		AdrGroup                   interface{} `json:"AdrGroup"`
		AdrNo                      string      `json:"AdrNo"`
		Birth                      time.Time   `json:"Birth"`
		CO2MaxOverpayment          int         `json:"CO2MaxOverpayment"`
		CO2MaxRepayment            int         `json:"CO2MaxRepayment"`
		CO2PricePerGramOverpayment int         `json:"CO2PricePerGramOverpayment"`
		CO2PricePerGramRepayment   int         `json:"CO2PricePerGramRepayment"`
		City                       string      `json:"City"`
		CreditratingDate           interface{} `json:"CreditratingDate"`
		CreditratingIndex          interface{} `json:"CreditratingIndex"`
		Delivery                   bool        `json:"Delivery"`
		DeliveryAddresses          []struct {
			City                  string      `json:"City"`
			Email                 interface{} `json:"Email"`
			Employer              string      `json:"Employer"`
			Firstname             interface{} `json:"Firstname"`
			GeoLat                float64     `json:"GeoLat"`
			GeoLong               float64     `json:"GeoLong"`
			Ident                 string      `json:"Ident"`
			Interlocutor          interface{} `json:"Interlocutor"`
			InterlocutorEmail     interface{} `json:"InterlocutorEmail"`
			InterlocutorFirstname interface{} `json:"InterlocutorFirstname"`
			InterlocutorNotes     interface{} `json:"InterlocutorNotes"`
			InterlocutorSalut     interface{} `json:"InterlocutorSalut"`
			Name1                 string      `json:"Name1"`
			Name2                 interface{} `json:"Name2"`
			Phone1                string      `json:"Phone1"`
			Phone2                interface{} `json:"Phone2"`
			Phoneinterlocutor     interface{} `json:"Phoneinterlocutor"`
			Salut                 interface{} `json:"Salut"`
			Street                string      `json:"Street"`
			ToBeDeleted           interface{} `json:"ToBeDeleted"`
			Zip                   string      `json:"Zip"`
		} `json:"DeliveryAddresses"`
		Email            string      `json:"Email"`
		Employer         interface{} `json:"Employer"`
		ExternalSourceID interface{} `json:"ExternalSourceId"`
		Extnumber        string      `json:"Extnumber"`
		ExtraProperties  struct {
			Budget                    interface{}   `json:"Budget"`
			CO2Budget                 interface{}   `json:"CO2Budget"`
			CompanyLogo               interface{}   `json:"CompanyLogo"`
			CreditratingDateTime      interface{}   `json:"CreditratingDateTime"`
			CreditratingLabel         interface{}   `json:"CreditratingLabel"`
			CreditratingRisk          interface{}   `json:"CreditratingRisk"`
			CreditratingScoreInfoText interface{}   `json:"CreditratingScoreInfoText"`
			CreditratingScoreText     interface{}   `json:"CreditratingScoreText"`
			CreditratingScoreValue    interface{}   `json:"CreditratingScoreValue"`
			CreditratingSource        interface{}   `json:"CreditratingSource"`
			CreditratingStatus        interface{}   `json:"CreditratingStatus"`
			CreditratingUser          interface{}   `json:"CreditratingUser"`
			EmailAddressVerified      bool          `json:"EmailAddressVerified"`
			ImageLinksLicense         []interface{} `json:"ImageLinksLicense"`
			ImageLinksPass            []interface{} `json:"ImageLinksPass"`
			LicenseCheckStatus        string        `json:"LicenseCheckStatus"`
			LicenseCheckedBy          interface{}   `json:"LicenseCheckedBy"`
			LicenseCheckedDate        interface{}   `json:"LicenseCheckedDate"`
			LicenseValidTo            interface{}   `json:"LicenseValidTo"`
			PassCheckStatus           string        `json:"PassCheckStatus"`
			PassCheckedBy             interface{}   `json:"PassCheckedBy"`
			PassCheckedDate           interface{}   `json:"PassCheckedDate"`
			PassValidTo               interface{}   `json:"PassValidTo"`
			ReservationAllowed        bool          `json:"ReservationAllowed"`
			StateInfoText             interface{}   `json:"StateInfoText"`
		} `json:"ExtraProperties"`
		Firstname             string      `json:"Firstname"`
		GeoLat                float64     `json:"GeoLat"`
		GeoLong               float64     `json:"GeoLong"`
		Ident                 string      `json:"Ident"`
		Inactive              bool        `json:"Inactive"`
		Interlocutor          interface{} `json:"Interlocutor"`
		InterlocutorEmail     interface{} `json:"InterlocutorEmail"`
		InterlocutorFirstname interface{} `json:"InterlocutorFirstname"`
		InterlocutorNotes     interface{} `json:"InterlocutorNotes"`
		InterlocutorSalut     interface{} `json:"InterlocutorSalut"`
		InvoiceReceiver       interface{} `json:"InvoiceReceiver"`
		Licauthor             string      `json:"Licauthor"`
		Licclasses            string      `json:"Licclasses"`
		Licdate               time.Time   `json:"Licdate"`
		Licno                 string      `json:"Licno"`
		Name1                 string      `json:"Name1"`
		Name2                 interface{} `json:"Name2"`
		Nationality           string      `json:"Nationality"`
		Newsletter            bool        `json:"Newsletter"`
		OwnedPolicies         interface{} `json:"OwnedPolicies"`
		ParentAddress         struct {
			City                          string      `json:"City"`
			CompanyPolicyDocumentsEnabled bool        `json:"CompanyPolicyDocumentsEnabled"`
			Employer                      interface{} `json:"Employer"`
			ExtraProperties               struct {
				CompanyLogo struct {
					Filename   string    `json:"Filename"`
					ImageIdent string    `json:"ImageIdent"`
					ImageLink  string    `json:"ImageLink"`
					Text       string    `json:"Text"`
					UploadDate time.Time `json:"UploadDate"`
				} `json:"CompanyLogo"`
				CreditratingDateTime      interface{}   `json:"CreditratingDateTime"`
				CreditratingLabel         interface{}   `json:"CreditratingLabel"`
				CreditratingRisk          interface{}   `json:"CreditratingRisk"`
				CreditratingScoreInfoText interface{}   `json:"CreditratingScoreInfoText"`
				CreditratingScoreText     interface{}   `json:"CreditratingScoreText"`
				CreditratingScoreValue    interface{}   `json:"CreditratingScoreValue"`
				CreditratingSource        interface{}   `json:"CreditratingSource"`
				CreditratingStatus        interface{}   `json:"CreditratingStatus"`
				CreditratingUser          interface{}   `json:"CreditratingUser"`
				CustomerAreaAllowed       bool          `json:"CustomerAreaAllowed"`
				CustomerAreaMode          interface{}   `json:"CustomerAreaMode"`
				EmailAddressVerified      bool          `json:"EmailAddressVerified"`
				ImageLinksLicense         []interface{} `json:"ImageLinksLicense"`
				ImageLinksPass            []interface{} `json:"ImageLinksPass"`
				LicenseCheckStatus        interface{}   `json:"LicenseCheckStatus"`
				LicenseCheckedBy          interface{}   `json:"LicenseCheckedBy"`
				LicenseCheckedDate        interface{}   `json:"LicenseCheckedDate"`
				LicenseValidTo            interface{}   `json:"LicenseValidTo"`
				Note                      interface{}   `json:"Note"`
				PassCheckStatus           interface{}   `json:"PassCheckStatus"`
				PassCheckedBy             interface{}   `json:"PassCheckedBy"`
				PassCheckedDate           interface{}   `json:"PassCheckedDate"`
				PassValidTo               interface{}   `json:"PassValidTo"`
				PaymentCondition          struct {
					BankRate     int         `json:"BankRate"`
					Disdays      int         `json:"Disdays"`
					Dispercent   int         `json:"Dispercent"`
					Ident        interface{} `json:"Ident"`
					Name1        interface{} `json:"Name1"`
					Netdays      int         `json:"Netdays"`
					Nowarning    bool        `json:"Nowarning"`
					Paymentkind  interface{} `json:"Paymentkind"`
					Text0        interface{} `json:"Text0"`
					TextGS       interface{} `json:"TextGS"`
					TextRG       interface{} `json:"TextRG"`
					Tolawyerdays int         `json:"Tolawyerdays"`
					Warndays1    int         `json:"Warndays1"`
					Warndays2    int         `json:"Warndays2"`
					Warndays3    int         `json:"Warndays3"`
					Warnextra1   int         `json:"Warnextra1"`
					Warnextra2   int         `json:"Warnextra2"`
					Warnextra3   int         `json:"Warnextra3"`
				} `json:"PaymentCondition"`
				ReservationAllowed             bool `json:"ReservationAllowed"`
				SimpleOnlinereservationAllowed bool `json:"SimpleOnlinereservationAllowed"`
			} `json:"ExtraProperties"`
			HideCompanyRentalPrices bool        `json:"HideCompanyRentalPrices"`
			Ident                   string      `json:"Ident"`
			Interlocutor            string      `json:"Interlocutor"`
			InterlocutorEmail       string      `json:"InterlocutorEmail"`
			InterlocutorFirstname   string      `json:"InterlocutorFirstname"`
			InterlocutorNotes       string      `json:"InterlocutorNotes"`
			Name1                   string      `json:"Name1"`
			Phone1                  interface{} `json:"Phone1"`
			Phoneinterlocutor       string      `json:"Phoneinterlocutor"`
			Street                  string      `json:"Street"`
			Zip                     string      `json:"Zip"`
		} `json:"ParentAddress"`
		Passauthor           interface{}   `json:"Passauthor"`
		Passdate             interface{}   `json:"Passdate"`
		Passno               interface{}   `json:"Passno"`
		Phone1               string        `json:"Phone1"`
		Phone2               interface{}   `json:"Phone2"`
		Phoneinterlocutor    interface{}   `json:"Phoneinterlocutor"`
		Policy               interface{}   `json:"Policy"`
		PreferredLanguage    interface{}   `json:"PreferredLanguage"`
		Salut                string        `json:"Salut"`
		Station              string        `json:"Station"`
		StoredPaymentMethods []interface{} `json:"StoredPaymentMethods"`
		Street               string        `json:"Street"`
		ToBeDeleted          interface{}   `json:"ToBeDeleted"`
		Zip                  string        `json:"Zip"`
	} `json:"Content"`
	Message    string `json:"Message"`
	ResultCode string `json:"ResultCode"`
	Success    bool   `json:"Success"`
}
