package dto

type UserInfo struct {
	StoredPaymentMethods       []interface{}     `json:"StoredPaymentMethods"`
	PreferredLanguage          interface{}       `json:"PreferredLanguage"`
	Inactive                   bool              `json:"Inactive"`
	AddressToken               string            `json:"AddressToken"`
	CreditratingDate           interface{}       `json:"CreditratingDate"`
	CreditratingIndex          interface{}       `json:"CreditratingIndex"`
	Delivery                   bool              `json:"Delivery"`
	Extnumber                  string            `json:"Extnumber"`
	CO2PricePerGramOverpayment int64             `json:"CO2PricePerGramOverpayment"`
	CO2PricePerGramRepayment   int64             `json:"CO2PricePerGramRepayment"`
	CO2MaxOverpayment          int64             `json:"CO2MaxOverpayment"`
	CO2MaxRepayment            int64             `json:"CO2MaxRepayment"`
	InvoiceReceiver            interface{}       `json:"InvoiceReceiver"`
	ExtraProperties            ExtraProperties   `json:"ExtraProperties"`
	DeliveryAddresses          []DeliveryAddress `json:"DeliveryAddresses"`
	ParentAddress              ParentAddress     `json:"ParentAddress"`
	Policy                     interface{}       `json:"Policy"`
	OwnedPolicies              interface{}       `json:"OwnedPolicies"`
	AddressRole                AddressRole       `json:"AddressRole"`
	Station                    string            `json:"Station"`
	AdrNo                      string            `json:"AdrNo"`
	AdrGroup                   interface{}       `json:"AdrGroup"`
	Newsletter                 bool              `json:"Newsletter"`
	Birth                      string            `json:"Birth"`
	Licno                      string            `json:"Licno"`
	Licdate                    string            `json:"Licdate"`
	Licauthor                  string            `json:"Licauthor"`
	Licclasses                 string            `json:"Licclasses"`
	Passno                     interface{}       `json:"Passno"`
	Passdate                   interface{}       `json:"Passdate"`
	Passauthor                 interface{}       `json:"Passauthor"`
	ExternalSourceID           interface{}       `json:"ExternalSourceId"`
	Ident                      string            `json:"Ident"`
	ToBeDeleted                interface{}       `json:"ToBeDeleted"`
	Salut                      string            `json:"Salut"`
	Name1                      string            `json:"Name1"`
	Name2                      interface{}       `json:"Name2"`
	Firstname                  string            `json:"Firstname"`
	Street                     string            `json:"Street"`
	Zip                        string            `json:"Zip"`
	City                       string            `json:"City"`
	Phone1                     string            `json:"Phone1"`
	Nationality                string            `json:"Nationality"`
	Phone2                     interface{}       `json:"Phone2"`
	Email                      string            `json:"Email"`
	InterlocutorFirstname      interface{}       `json:"InterlocutorFirstname"`
	InterlocutorSalut          interface{}       `json:"InterlocutorSalut"`
	InterlocutorEmail          interface{}       `json:"InterlocutorEmail"`
	Phoneinterlocutor          interface{}       `json:"Phoneinterlocutor"`
	Interlocutor               interface{}       `json:"Interlocutor"`
	InterlocutorNotes          interface{}       `json:"InterlocutorNotes"`
	Employer                   interface{}       `json:"Employer"`
	GeoLat                     float64           `json:"GeoLat"`
	GeoLong                    float64           `json:"GeoLong"`
}
